language: node_js
node_js:
- lts/*
- node
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAUBQC5BRR7P2OGMWT
  - secure: "Cj3AlP0LjKZdRX112MEjqrC1UH8zOm7jh2eDg+9LHJHzF+sKvkidbqrL5yclgTIrmFrzI+nkKvU+yPrrZhIPd31n61QAowrqZ6bbm/+cFKuBO0i3jTVBge+RHrFcFJ1xsvc8PqWXPi5AfK/lh2NS2dJVPZIm51Rk+DuQo6zqVGQpG10N4EcNLJG6aE2C56u/at95yPluu/wSEU395rBaXM6Fn6//YcjwBmeauM6mRT9Odjc/TJ1GrlZl2NxKIz1vPcaY1Qf32TvhxBVE77L4iUdKksZnULKVLgiiBzGB1dp12gWIRbWg2RHy3ZNllsnLoFWnK7Aa5jics0QbjEy/nYL2H8fQhhOnN4RUxiJRav8cvszZoqEkGy5iSpYsvYMuLJOdTbHZ5RdTVzVFaW28B8LzvRbGk0a4Ei/pN3fewWulSd9MpYYX/GnyE/X7BBno95RGHArSgao1ElqB1/1OoOfC5EQd9LWbn/uWlaprhsy6JjsF/Vfuwd5a6+UgMisfMtAConao20c2iAlh10aRpy2cXBQqoZOfWoArgtqxHPrY4mnluODYxJd3pkhBafR6jJ/OcuD8yjHexvwSHYTfCwuZQwiqiwpd+ZXgREEkA81i+P8gu3fGalOatPaH55mRcYUAglQfTlY/7iW/1U/yI5u6QG+cAx0d/dqb7Ng4xp4="
