language: node_js
node_js:
- lts/*
- node
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAIO7CKKFMB34NLUUQ
  - secure: iGLlmJwaImqX9C8djNWsfmzbonb7QqEhjXMwkVdJ95m7XVKONsktBCPFNK0eRU8FdnwShGrRs84JAYvHUx3klpEr7SLjtGClTkatRkuzFUz7AB1mGO1JgVUhfFU4uTuR2TlXNxcVUbNRdunBBSrjpvbFwIxIxe987n6SVLJ9Nsvi10y2e0VIXy4QnvVWlAVtWBkGxDAtCsiA/Wkn8UGmdHw4AwXhNUFKdypJ1kE2PaxyQ/SvZYEGvYM6F/La53TY39Eh+fr/ncTa69ezG2wTiCMVwAQFcUdtFjuMXP4ZEV0mNqXRs+WJLWgrVwWdsfEg852W5DGt80BGDMoPaDw46v1wLiN3afz+CrXfzl3DhG0P5lD9/XqFwqTJEa+PpFYFN7F2c8FcpLvdkTDUkAIF1vpfwSA1KcbBtcLQS7Tfgrsy4yZ4TqnStyhyUM/v8chAVqc8o6Z/z7QJw/9/SElyRkW5Xl4dYu5YxlGVQutSvLh6RdMb6S60maCQYizDbP1dRoufr+Q0vcSCJBkipSF6J5pCNpJubmezi2S0YDGAdgVFlJ2BUAaYV7ca5jhydKGHXasBTJDtM7tzhIX5dR57C0lsA0/OeP11DpY2c/Cm0tjsY4pN91gPk+3NKwbY78a8AysIwcLNbTdmxwiIhWUgCByE2xO9pCFg/+RS7qcQrWw=
